[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "github.com/gobwas/glob"
  version = "0.2.3"

[[constraint]]
  name = "github.com/karrick/godirwalk"
  version = "1.7.5"

[[constraint]]
  name = "github.com/google/go-cmp"
  version = "0.2.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[prune]
  go-tests = true
  unused-packages = true
